/*
	    Author: Bragg for 197th Compagnie Chimaera
	
	    Description: Please do not [Copy, Modify, Plagiarize] the following content without prior authorization from its creator.
	    
	    Website: [www.197th.fr]
*/

private _LoadoutParametres = [
	[
		"197th_Loadout_AA",
		[
			["AA\DC15S","DC-15S"]
		]
	],
	[
		"197th_Loadout_ARC",
		[
			["ARC\DC15A","DC-15A"],
			["ARC\DC15S","DC-15S"]
		]
	],
	[
		"197th_Loadout_ARF",
		[
			["ARF\DC15X","DC-15X"]
		]
	],
	[
		"197th_Loadout_AT",
		[
			["AT\DC15S","DC-15S"]
		]
	],
	[
		"197th_Loadout_Fantassin",
		[
			["Cadet\DC15A","DC-15A"],
			["Cadet\DC15S","DC-15S"],
			["Fantassin\DC15A","DC-15A"],
			["Fantassin\DC15S","DC-15S"],
			["Leader\DC15A","DC-15A"],
			["Leader\DC15S","DC-15S"]
		]
	],
	[
		"197th_Loadout_Grenadier",
		[
			["Grenadier\DC15A","DC-15A"]
		]
	],
	[
		"197th_Loadout_Heavy",
		[
			["Heavy\Z6","Rotary Z-6"]
		]
	],
	[
		"197th_Loadout_Medecin",
		[
			["Infirmier\DC15A","DC-15A"],
			["Infirmier\DC15S","DC-15S"],
			["Medecin\DC15A","DC-15A"],
			["Medecin\DC15S","DC-15S"]
		]
	],
	[
		"197th_Loadout_Pilote",
		[
			["Pilote\DC17SA","DC-17SA"]
		]
	],
	[
		"197th_Loadout_Radioman",
		[
			["Radioman\DC15A","DC-15A"]
		]
	],
	[
		"197th_Loadout_Sapeur",
		[
			["Sapeur\DC15A","DC-15A"],
			["Sapeur\DC15S","DC-15S"]
		]
	],
	[
		"197th_Loadout_Shield",
		[
			["Shield\DC15S","DC-15S"]
		]
	]
];